[project]
name = "auspex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
    "pytest>=9.1.1",
    "tqdm>=4.70.0",
]

#essentaily names the thing that  turns code into package like in venv
[build-system]
#hatchling does it
requires = ["hatchling"]
build-backend="hatchling.build"

#just to tell which code to be made into package
[tool.hatch.build.targets.wheel]
packages = ["src/auspex"]

[dependency-groups]
dev = [
    "pandas-stubs>=3.0.5.260730",
]
